package com.example.myaku_rismu.ui.theme

import androidx.compose.ui.graphics.Color

data class CustomTheme(
    val healthDetailMoveThemeColor: Color,
    val healthDetailMoveDistanceThemeColor: Color,
    val healthDetailHeartRateThemeColor: Color,
    val healthDetailSleepThemeColor: Color,
    val healthDetailWalkThemeColor: Color,
    val healthDetailPeriodTabColor: Color,
    val healthDetailSelectedPeriodTabColor: Color,
    val settingScreenTextColor: Color,
    val settingScreenCardColor: Color,
    val settingScreenBackgroundColor: Color,
    val settingScreenCommonColor: Color,
    val onSelectedButtonOverlay: Color,
    val bottomNavigationBarBackgroundColor: Color,
    val bottomNavigationBarSelectedColor: Color,
    val bottomNavigationBarUnSelectedColor: Color,
    val homeLowBpmColor: Color,
    val homeMediumBpmColor: Color,
    val homeHighBpmColor: Color,
    val homeHeartRateColor: Color,
    val homeMoveColor: Color,
    val homeStepsColor: Color,
    val homeSleepColor: Color,
    val homeDistanceColor: Color,
    val homeHeartRateBarColorFaded: Color,
    val homeMoveBarColorFaded: Color,
    val homeStepsBarColorFaded: Color,
    val homeSleepBarColorFaded: Color,
    val homeDistanceBarColorFaded: Color,
    val homeLowBpmRippleColor: Color,
    val homeMediumBpmRippleColor: Color,
    val homeHighBpmRippleColor: Color,
)
