package com.example.myaku_rismu.ui.theme

import androidx.compose.ui.graphics.Color

data class CustomTheme(
    val myakuRismuBackgroundColor: Color,
    val myakuRismuCardColor: Color,
    val healthDetailMoveThemeColor: Color,
    val healthDetailMoveDistanceThemeColor: Color,
    val healthDetailHeartRateThemeColor: Color,
    val healthDetailSleepThemeColor: Color,
    val healthDetailWalkThemeColor: Color,
    val healthDetailPeriodTabColor: Color,
    val settingScreenCommonColor: Color,
    val settingScreenNormalTextColor: Color,
    val onSelectedButtonOverlay: Color,
    val healthDetailSelectedPeriodTabColor: Color,
    val settingScreenBackgroundColor: Color,
    val bottomNavigationBarBackgroundColor: Color,
    val bottomNavigationBarSelectedColor: Color,
    val bottomNavigationBarUnSelectedColor: Color,
    val switchCheckedThumbColor: Color,
    val switchUncheckedThumbColor: Color,
    val switchCheckedTrackColor: Color,
    val switchUncheckedTrackColor: Color,
    val appTextColor: Color,
    val musicDetailMiniMusicPlayerBackgroundColor: Color,
    val musicDetailMusicPlayerFavorite: Color,
    val musicDetailMusicPlayerShuffle: Color,
    val musicDetailSettingTarget: Color,
    val disabledBackgroundColor: Color,
    val buttonBackgroundColor: Color,
    val homeLowBpmColor: Color,
    val homeMediumBpmColor: Color,
    val homeHighBpmColor: Color,
    val homeHeartRateBarColorFaded: Color,
    val homeMoveBarColorFaded: Color,
    val homeWalkBarColorFaded: Color,
    val homeSleepBarColorFaded: Color,
    val homeMoveDistanceBarColorFaded: Color,
    val homeLowBpmRippleColor: Color,
    val homeMediumBpmRippleColor: Color,
    val homeHighBpmRippleColor: Color,
    val loadingTextColor: Color

)
